{% set name = "ssh-audit" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ebbad6b5e9e0ad930e8d2d7034f890605a461ad52bf7021a09fd9edf17945e31

build:
  entry_points:
    - ssh-audit = ssh_audit.ssh_audit:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8,<4.0

test:
  imports:
    - ssh_audit
  commands:
    - pip check
    - ssh-audit --help
  requires:
    - pip

about:
  home: https://github.com/jtesta/ssh-audit
  summary: An SSH server & client configuration security auditing tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
